### ISSUE TITLE
Non-unique path assertion in `follow_path`

### ISSUE THREAD

**Issue by lassepe** [brianguenter/FastDifferentiation.jl#40] opened 2023-08-28 15:18 UTC
Some code of mine hits the following assertion:

https://github.com/brianguenter/FastDifferentiation.jl/blob/34325511369d200d8a21529ab04e5d86586bea2f/src/Factoring.jl#L512

**Steps to Reproduce**

While I cannot share a "from scratch"-reproducer, I did manage to capture the offending inputs in a JLD2 file. I uploaded the full reproducer including a  Manifest.toml etc here:
https://github.com/lassepe/bugreport-FastDifferentiation.jl-nonunique-path

Alternatively, one can run the following steps manually to reproduce the issue:

1. Download and unpack the the JLD2 file containing the offending inputs: [reproducer.zip](https://github.com/brianguenter/FastDifferentiation.jl/files/12456113/reproducer.zip)

2. Load the inputs and try to compute a sparse jacobian:

```julia
using JLD2: JLD2
using FastDifferentiation: FastDifferentiation as FD

erroneous_inputs = JLD2.load_object("fd_error_inputs.jld2")
(; f_node, z_node) = erroneous_inputs
# this hits an assertion
# ERROR: LoadError: AssertionError: Should only be one path from root 1 to variable 6. Instead have 2 children from node 65 on the path
FD.sparse_jacobian(f_node, z_node)
```

This results in the following error:

```julia
ERROR: LoadError: AssertionError: Should only be one path from root 1 to variable 6. Instead have 2 children from node 65 on the path
```

**Comment by lassepe** [comment] 2023-08-28 16:10
By manually bisecting the children of `f_node` above, I managed to create another, smaller reproducer:
[reproducer.zip](https://github.com/brianguenter/FastDifferentiation.jl/files/12456306/reproducer.zip)

**Comment by brianguenter** [comment] 2023-08-28 22:19
Thank you for the bug report and for taking the time to reduce it to the smallest possible example. 

I've isolated the error, it's in the code that updates variable and root reachability. It might take a while to track down exactly what is going wrong since this is the most complex code of the project.

**Comment by lassepe** [comment] 2023-09-11 21:24
Here's an even more reduced test case that does not involve any additional dependencies. It may be worth adding this to the test suite with `@test_broken`

```julia
using FastDifferentiation: FastDifferentiation as FD

x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11 = x = FD.make_variables(:x, 11)

f = [
    (exp(((x11 * (x4 - sqrt(((((((x2 - x8) ^ 2) + ((x5 - x6) ^ 2)) + ((x1 - x9) ^ 2)) + ((x3 - x10) ^ 2)) + x7)))) - (((x4 - sqrt(((((((x2 - x8) ^ 2) + ((x5 - x6) ^ 2)) + ((x1 - x9) ^ 2)) + ((x3 - x10) ^ 2)) + x7))) * x11) / 2))) + exp(-((((x4 - sqrt(((((((x2 - x8) ^ 2) + ((x5 - x6) ^ 2)) + ((x1 - x9) ^ 2)) + ((x3 - x10) ^ 2)) + x7))) * x11) / 2)))),
   ((-(exp(((x11 * (x4 - sqrt(((((((x2 - x8) ^ 2) + ((x5 - x6) ^ 2)) + ((x1 - x9) ^ 2)) + ((x3 - x10) ^ 2)) + x7)))) - (((x4 - sqrt(((((((x2 - x8) ^ 2) + ((x5 - x6) ^ 2)) + ((x1 - x9) ^ 2)) + ((x3 - x10) ^ 2)) + x7))) * x11) / 2)))) + -(exp(-((((x4 - sqrt(((((((x2 - x8) ^ 2) + ((x5 - x6) ^ 2)) + ((x1 - x9) ^ 2)) + ((x3 - x10) ^ 2)) + x7))) * x11) / 2))))) * (1 / (exp(((x11 * (x4 - sqrt(((((((x2 - x8) ^ 2) + ((x5 - x6) ^ 2)) + ((x1 - x9) ^ 2)) + ((x3 - x10) ^ 2)) + x7)))) - (((x4 - sqrt(((((((x2 - x8) ^ 2) + ((x5 - x6) ^ 2)) + ((x1 - x9) ^ 2)) + ((x3 - x10) ^ 2)) + x7))) * x11) / 2))) + exp(-((((x4 - sqrt(((((((x2 - x8) ^ 2) + ((x5 - x6) ^ 2)) + ((x1 - x9) ^ 2)) + ((x3 - x10) ^ 2)) + x7))) * x11) / 2))))))

]

FD.sparse_jacobian(f, x)
```

<details><summary> Click to see error</summary>

```julia
julia> FD.sparse_jacobian(f, x)
ERROR: AssertionError: Should only be one path from root 1 to variable 7. Instead have 2 children from node 34 on the path
Stacktrace:
 [1] follow_path(a::FastDifferentiation.DerivativeGraph{Int64}, root_index::Int64, var_index::Int64)
   @ FastDifferentiation ~/worktree/FastDifferentiation.jl/src/Factoring.jl:519
 [2] evaluate_path
   @ FastDifferentiation ~/worktree/FastDifferentiation.jl/src/Factoring.jl:549 [inlined]
 [3] _sparse_symbolic_jacobian!(graph::FastDifferentiation.DerivativeGraph{Int64}, partial_variables::Vector{FastDifferentiation.Node})
   @ FastDifferentiation ~/worktree/FastDifferentiation.jl/src/Jacobian.jl:116
 [4] sparse_jacobian(terms::Vector{FastDifferentiation.Node}, partial_variables::Vector{FastDifferentiation.Node})
   @ FastDifferentiation ~/worktree/FastDifferentiation.jl/src/Jacobian.jl:136
 [5] top-level scope
   @ REPL[4]:1
 [6] top-level scope
   @ ~/.julia/packages/Infiltrator/LtFao/src/Infiltrator.jl:726
```

</details>

**Comment by brianguenter** [comment] 2023-09-11 23:32
@lassepe Thank you for that simpler test case. Will make my job of debugging this much easier.

**Comment by lassepe** [comment] 2023-09-12 09:09
FWIW, observe that `f` above has a very special structure. If we let

 `a = (exp(((x11 * (x4 - sqrt(((((((x2 - x8) ^ 2) + ((x5 - x6) ^ 2)) + ((x1 - x9) ^ 2)) + ((x3 - x10) ^ 2)) + x7)))) - (((x4 - sqrt(((((((x2 - x8) ^ 2) + ((x5 - x6) ^ 2)) + ((x1 - x9) ^ 2)) + ((x3 - x10) ^ 2)) + x7))) * x11) / 2))) + exp(-((((x4 - sqrt(((((((x2 - x8) ^ 2) + ((x5 - x6) ^ 2)) + ((x1 - x9) ^ 2)) + ((x3 - x10) ^ 2)) + x7))) * x11) / 2))))`,

then `f` can be written as

`f = [a, -a/a]`

To simplify this, FD would have to understand that `a` is positive due to exp, I guess. In fact, currently, FD produces this

```julia
julia> a = FastDifferentiation.make_variables(:a) |> only
a

julia> f = [a, -a/a]
2-element Vector{FastDifferentiation.Node}:
          a
 (-(a) / a)

julia> sparse_jacobian(f, [a])
2×1 SparseArrays.SparseMatrixCSC{FastDifferentiation.Node, Int64} with 2 stored entries:
                                  1
 (-((1 / a)) + -(((-(a) / a) / a)))
```

whereas Symbolics.jl immediately simplifies (even without knowing that `a` is non-zero):

```julia
julia> a = Symbolics.@variables(a) |> only
a

julia> f = [a, -a/a]
2-element Vector{Num}:
  a
 -1

julia> Symbolics.sparsejacobian(f, [a])
2×1 SparseArrays.SparseMatrixCSC{Num, Int64} with 1 stored entry:
 1
 ⋅
```

**Comment by lassepe** [comment] 2023-09-12 20:52
An even simpler reproducer in only 3 variables:

```julia
using FastDifferentiation: FastDifferentiation as FD

x1, x2, x3 = FD.make_variables(:x, 3)

f = [
    exp(sqrt((x1 - x2)^2) - sqrt((x1 - x2)^2) * x3) + exp(-(sqrt((x1 - x2)^2) * x3)),
    (-exp(sqrt((x1 - x2)^2) - sqrt((x1 - x2)^2) * x3) + -exp(-sqrt((x1 - x2)^2) * x3)) /
    (exp(sqrt((x1 - x2)^2) - sqrt((x1 - x2)^2) * x3) + exp(-(sqrt((x1 - x2)^2) * x3))),
]

FD.jacobian(f, [x1])
```

Interestingly, removing the redundant parentheses round the either of the `sqrt` expressions on the right causes the error to disappear.

**Comment by brianguenter** [comment] 2023-09-16 02:20
@lassepe  pretty sure I found the bug causing this problem, the subgraphs were being factored in the wrong order. Unfortunately the fix for this problem breaks other code. I'm working on that now. Thanks again for taking the time to make the MWE. That made it much easier to debug.

**Comment by brianguenter** [comment] 2023-09-23 00:30
I've found the new bug that was exposed by the fix for the "Non-unique path assertion" and have a fix for it. Working on it now, should be done in a week or less.

**Comment by brianguenter** [comment] 2023-10-04 01:24
Found more bugs exposed by fixes for bugs exposed by fix for non-unique path assertion. This has entailed rewriting most of the factorization code, which is gnarly and not quite done.

**Comment by brianguenter** [comment] 2023-10-10 16:25
Still working on the fix to the bugs exposed by the first fix. I thought there was a single bug root cause but there were many edge case bugs, all very subtle. I've had to rewrite the derivative graph factorization code to make it more robust. It has been slow going because the bugs only manifest in relatively large graphs, with hundreds or thousands of nodes. Very time consuming to step through the factorization to find which of hundreds of steps set a bit wrong.

**Comment by lassepe** [comment] 2023-10-11 07:42
Thank you for your perseverance! While I won't be able to contribute to the bug fixing efforts, please do let me know if I can assist with debugging / isolating failure cases in any way.

**Comment by ejmeitz** [comment] 2023-10-11 23:51
Can we be certain if we dont get this error that the derivatives are correct?

**Comment by brianguenter** [comment] 2023-10-12 02:28
The bugs causing this error are corrupting the reachability labels of edges in the derivative graph. If these labels are wrong the derivative is probably wrong. 

**FD** verifies the correctness of the reachability labels in a final postprocessing step so if you do not get one of these error messages the odds are good that the reachability labels are uncorrupted and your derivative is correct. 

A version of the code on a different branch has a stronger verification step than on the main branch. Once that verification code is thoroughly tested I will push it to the main branch.

Until the bugs are fixed if you want a higher degree of certainty then you can test against another AD package or FiniteDifferences.jl for your particular function.

**Comment by brianguenter** [comment] 2023-10-12 02:38
I am working hard to squash these bugs even though it may not look like it. Github insights shows no activity for the last several weeks because the new code is on the factororderfix branch and won't be pushed to the main branch till all tests pass. Only commits to the main branch show up in insights.

**Comment by lassepe** [comment] 2023-12-01 22:27
May I carefully ask for an update on this issue? Do you have a rough estimate how far out a potential fix is?

**Comment by brianguenter** [comment] 2023-12-02 08:09
Sure, I've been hacking away for quite a while. There were perhaps 8-12 very subtle bugs in the code that only manifest in unusual situations. IThe newest code has a mode that will verify the derivative at every factorization step. This is extremely slow so you would only do this to verify that your derviative is correct, or to file an issue by including the information the verification code prints when it finds an error.

Seem to be down to the last bug for which there is a solution but which I haven't coded yet. Work will slow down during the holidays so perhaps this bug will be fixed and pushed to the repo near the end of December.

**Comment by lassepe** [comment] 2024-03-18 10:31
Friendly quarterly bump :)

**Comment by brianguenter** [comment] 2024-03-19 04:38
Haven't forgotten. I needed to take a break from the code to work on other things. But I still intend to fix this bug and to add many new features. Wish I could give a more precise timeline but that's the nature of open source.

**Closed** 2024-04-25 17:47 UTC

**Comment by brianguenter** [comment] 2024-04-25 18:06
@laseppe I've moved your more complex MWE which still fails over to the new [PR](https://github.com/brianguenter/FastDifferentiation.jl/pull/66#issue-2204062899) so it won't be forgotten.

**Comment by lassepe** [comment] 2024-04-26 08:02
Thank you, @brianguenter! Some of the reproducers above have indeed been fixed by the last patch. Interestingly, the simplest MWE above still fails however:

```julia
using FastDifferentiation: FastDifferentiation as FD

x1, x2, x3 = FD.make_variables(:x, 3)

f = [
      x1 - x2 - (x1 - x2) * x3 + (x1 - x2) * x3,
      x1 - x2 - (x1 - x2) * x3 + (x1 - x2) * x3 /
     (x1 - x2 - (x1 - x2) * x3 + (x1 - x2) * x3),
]

FD.jacobian(f, [x1])
```

Do you think that this, too, is due to #65?

**Comment by brianguenter** [comment] 2024-04-26 16:53
I would be surprised if it is due to [#65](https://github.com/brianguenter/FastDifferentiation.jl/issues/65). I thought I had tested this MWE as well but it slipped through. Will look at it today.
